/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         *
         *     Returns application health status and basic info.
         *     This endpoint is always accessible (no auth required).
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get system statistics.
         *
         *     Returns comprehensive system information including:
         *     - CPU usage
         *     - Memory usage with status (ok/warning/critical)
         *     - Disk usage
         *     - CPU temperature (if available)
         *     - Throttle status (if on Raspberry Pi)
         *
         *     This endpoint is always accessible (no auth required).
         */
        get: operations["get_stats_api_v1_health_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cameras
         * @description List all cameras with optional filtering.
         *
         *     Args:
         *         session: Database session
         *         enabled_only: Only return enabled cameras
         *         camera_type: Filter by camera type ('csi' or 'usb')
         *         skip: Number of records to skip
         *         limit: Maximum number of records to return
         *
         *     Returns:
         *         List of cameras and total count
         */
        get: operations["list_cameras_api_v1_cameras_get"];
        put?: never;
        /**
         * Create Camera
         * @description Create a new camera.
         *
         *     Args:
         *         camera_data: Camera creation data
         *         session: Database session
         *
         *     Returns:
         *         Created camera
         *
         *     Raises:
         *         HTTPException: 409 if device_path already exists
         */
        post: operations["create_camera_api_v1_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Camera
         * @description Get a specific camera by ID.
         *
         *     Args:
         *         camera_id: Camera ID
         *         session: Database session
         *
         *     Returns:
         *         Camera details
         *
         *     Raises:
         *         HTTPException: 404 if camera not found
         */
        get: operations["get_camera_api_v1_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Camera
         * @description Delete a camera.
         *
         *     Args:
         *         camera_id: Camera ID
         *         session: Database session
         *
         *     Raises:
         *         HTTPException: 404 if camera not found
         */
        delete: operations["delete_camera_api_v1_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Camera
         * @description Update a camera.
         *
         *     Args:
         *         camera_id: Camera ID
         *         camera_data: Camera update data
         *         session: Database session
         *
         *     Returns:
         *         Updated camera
         *
         *     Raises:
         *         HTTPException: 404 if camera not found
         */
        patch: operations["update_camera_api_v1_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/v1/output-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Output Config
         * @description Get the current output configuration.
         *
         *     If no configuration exists, creates and returns default configuration.
         *
         *     Args:
         *         session: Database session
         *
         *     Returns:
         *         Output configuration
         */
        get: operations["get_output_config_api_v1_output_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Output Config
         * @description Update the output configuration.
         *
         *     Args:
         *         config_data: Configuration update data
         *         session: Database session
         *
         *     Returns:
         *         Updated output configuration
         */
        patch: operations["update_output_config_api_v1_output_config_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CameraCapabilities
         * @description Camera capabilities information.
         */
        CameraCapabilities: {
            /**
             * Resolutions
             * @description Supported resolutions (e.g., '1920x1080')
             */
            resolutions?: string[];
            /**
             * Formats
             * @description Supported formats (e.g., 'H264', 'MJPEG')
             */
            formats?: string[];
            /**
             * Framerates
             * @description Supported framerates (fps)
             */
            framerates?: number[];
        };
        /**
         * CameraCreate
         * @description Schema for creating a camera.
         */
        CameraCreate: {
            /**
             * Name
             * @description Camera name
             */
            name: string;
            /**
             * Device Path
             * @description Device path (e.g., /dev/video0)
             */
            device_path: string;
            /**
             * Camera Type
             * @description Camera type: 'csi' or 'usb'
             */
            camera_type: string;
            /**
             * Enabled
             * @description Whether camera is enabled
             * @default true
             */
            enabled: boolean;
            /** @description Camera capabilities */
            capabilities?: components["schemas"]["CameraCapabilities"] | null;
            /** @description Default camera settings */
            default_settings?: components["schemas"]["CameraSettings"] | null;
        };
        /**
         * CameraListResponse
         * @description Schema for camera list response.
         */
        CameraListResponse: {
            /** Cameras */
            cameras?: components["schemas"]["CameraResponse"][];
            /**
             * Total
             * @description Total number of cameras
             */
            total: number;
        };
        /**
         * CameraResponse
         * @description Schema for camera response.
         */
        CameraResponse: {
            /**
             * Name
             * @description Camera name
             */
            name: string;
            /**
             * Device Path
             * @description Device path (e.g., /dev/video0)
             */
            device_path: string;
            /**
             * Camera Type
             * @description Camera type: 'csi' or 'usb'
             */
            camera_type: string;
            /**
             * Enabled
             * @description Whether camera is enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Id
             * @description Camera ID
             */
            id: number;
            capabilities?: components["schemas"]["CameraCapabilities"] | null;
            default_settings?: components["schemas"]["CameraSettings"] | null;
        };
        /**
         * CameraSettings
         * @description Default camera settings.
         */
        CameraSettings: {
            /**
             * Resolution
             * @description Default resolution
             */
            resolution?: string | null;
            /**
             * Framerate
             * @description Default framerate (fps)
             */
            framerate?: number | null;
            /**
             * Format
             * @description Default format
             */
            format?: string | null;
            /**
             * Brightness
             * @description Brightness (0-100)
             */
            brightness?: number | null;
            /**
             * Contrast
             * @description Contrast (0-100)
             */
            contrast?: number | null;
            /**
             * Saturation
             * @description Saturation (0-100)
             */
            saturation?: number | null;
        };
        /**
         * CameraUpdate
         * @description Schema for updating a camera (all fields optional).
         */
        CameraUpdate: {
            /** Name */
            name?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            default_settings?: components["schemas"]["CameraSettings"] | null;
        };
        /**
         * DiskInfo
         * @description Disk statistics.
         */
        DiskInfo: {
            /** Path */
            path: string;
            /** Total Gb */
            total_gb: number;
            /** Used Gb */
            used_gb: number;
            /** Free Gb */
            free_gb: number;
            /** Percent Used */
            percent_used: number;
            /** Is Available */
            is_available: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /**
         * MemoryInfo
         * @description Memory statistics.
         */
        MemoryInfo: {
            /** Total Mb */
            total_mb: number;
            /** Available Mb */
            available_mb: number;
            /** Used Mb */
            used_mb: number;
            /** Percent */
            percent: number;
            /** Status */
            status: string;
        };
        /**
         * Meta
         * @description Response metadata.
         */
        Meta: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * OutputConfigResponse
         * @description Schema for output configuration response.
         */
        OutputConfigResponse: {
            /**
             * Recording Base Path
             * @description Base directory for recordings
             * @default /var/lib/timemachine/recordings
             */
            recording_base_path: string;
            /**
             * Still Base Path
             * @description Base directory for still captures
             * @default /var/lib/timemachine/stills
             */
            still_base_path: string;
            /**
             * Timelapse Base Path
             * @description Base directory for timelapses
             * @default /var/lib/timemachine/timelapse
             */
            timelapse_base_path: string;
            /**
             * Retention Days
             * @description Number of days to retain recordings
             * @default 7
             */
            retention_days: number;
            /**
             * Max Storage Gb
             * @description Maximum storage usage in GB
             * @default 50
             */
            max_storage_gb: number;
            /**
             * Id
             * @description Configuration ID
             */
            id: number;
        };
        /**
         * OutputConfigUpdate
         * @description Schema for updating output configuration (all fields optional).
         */
        OutputConfigUpdate: {
            /** Recording Base Path */
            recording_base_path?: string | null;
            /** Still Base Path */
            still_base_path?: string | null;
            /** Timelapse Base Path */
            timelapse_base_path?: string | null;
            /** Retention Days */
            retention_days?: number | null;
            /** Max Storage Gb */
            max_storage_gb?: number | null;
        };
        /** ResponseWrapper[HealthResponse] */
        ResponseWrapper_HealthResponse_: {
            data: components["schemas"]["HealthResponse"];
            meta?: components["schemas"]["Meta"];
        };
        /** ResponseWrapper[StatsResponse] */
        ResponseWrapper_StatsResponse_: {
            data: components["schemas"]["StatsResponse"];
            meta?: components["schemas"]["Meta"];
        };
        /**
         * StatsResponse
         * @description System statistics response.
         */
        StatsResponse: {
            /** Cpu Percent */
            cpu_percent: number;
            memory: components["schemas"]["MemoryInfo"];
            disk: components["schemas"]["DiskInfo"];
            /** Temperature Celsius */
            temperature_celsius: number | null;
            throttle: components["schemas"]["ThrottleInfo"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * ThrottleInfo
         * @description Throttle status information.
         */
        ThrottleInfo: {
            /** Available */
            available: boolean;
            /** Raw Value */
            raw_value?: string | null;
            /**
             * Is Throttled
             * @default false
             */
            is_throttled: boolean;
            /** Active */
            active?: string[] | null;
            /** Historical */
            historical?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseWrapper_HealthResponse_"];
                };
            };
        };
    };
    get_stats_api_v1_health_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseWrapper_StatsResponse_"];
                };
            };
        };
    };
    list_cameras_api_v1_cameras_get: {
        parameters: {
            query?: {
                enabled_only?: boolean;
                camera_type?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_camera_api_v1_cameras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_camera_api_v1_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_output_config_api_v1_output_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputConfigResponse"];
                };
            };
        };
    };
    update_output_config_api_v1_output_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutputConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
